project:
  type: website
  output-dir: docs
  
website:
  title: "SUPPLY CHAIN MANAGEMENT"
  navbar: 
    left:
      - href: index.qmd
        text: Introduction
      - href: projects.qmd
        text: ABC analyst
      - href: reactable.qmd
        text: Report concepts
      - href: spatial.qmd
        text: Geocomputation in R
    tools:
      - icon: github
        text: Github
        href: https://github.com/Loccx78vn/Quarto
      - icon: twitter
        text: Another projects
        href: https://rpubs.com/loccx
        
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Loc cao"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true

editor: source